src/SimpleIT/ClaireExerciseBundle/Entity/AskerUserDirectory.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * AskerUserDirectory
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="SimpleIT\ClaireExerciseBundle\Entity\AskerUserDirectoryRepository")
 */
class AskerUserDirectory
{

    public function __construct()
    {
        $this->startDate = new \DateTime();
    }
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;



    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startDate", type="datetime")
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="endDate", type="datetime")
     */
    private $endDate = null;

    /**
     * @var boolean
     *
     * @ORM\Column(name="isManager", type="boolean")
     */
    private $isManager;

    /**
     * @var boolean
     *
     * @ORM\Column(name="isReader", type="boolean")
     */
    private $isReader;

    /**
     *
     *
     *  @ORM\JoinColumn(nullable=false)
     */
    private $directory;

    /**
     *
     *
     *  @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get directory.
     *
     * @return directory.
     */
    public function getDirectory()
    {
        return $this->directory;
    }

    /**
     * Set directory.
     *
     * @param directory the value to set.
     */
    public function setDirectory($directory)
    {
        $this->directory = $directory;
    }

    /**
     * Get user.
     *
     * @return user.
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set user.
     *
     * @param user the value to set.
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    #public function isOnlyStudent()
    #{

    #    foreach($this->getUser()->getRoles() as $role){
    #        $name = $role->getName();
    #        if (!preg_match( "/.*ROLE_USER.*/",$name)){
    #            return false;
    #        }
    #    }
    #    return true;
    #}

    #public function getUserId()
    #{
    #    return $this->getUser()->getId();
    #}

    public function __toString()
    {
        return "objet AskerUserDirectory: dName:".$this->getDirectory()->getName(). "id:" .$this->getId(). "uname:" .$this->getUser()->getUsername();
    }
    /**
     * Get isManager.
     *
     * @return isManager.
     */
    public function getIsManager()
    {
        return $this->isManager;
    }

    /**
     * Set isManager.
     *
     * @param isManager the value to set.
     */
    public function setIsManager($isManager)
    {
        $this->isManager = $isManager;
    }
    /**
     * Get isReader.
     *
     * @return isReader.
     */
    public function getIsReader()
    {
        return $this->isReader;
    }

    /**
     * Set isReader.
     *
     * @param isReader the value to set.
     */
    public function setIsReader($isReader)
    {
        $this->isReader = $isReader;
    }
    /**
     * Get startDate.
     *
     * @return startDate.
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set startDate.
     *
     * @param startDate the value to set.
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;
    }

    /**
     * Get endDate.
     *
     * @return endDate.
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set endDate.
     *
     * @param endDate the value to set.
     */
    public function setEndDate($endDate = null)
    {
        $this->endDate = $endDate;
    }
    public function isOwner(){
        if ($this->getDirectory()->getOwner()->getId() == $this->getUser()->getId()){
            return true;
        }
        return false;
    }

}

src/SimpleIT/ClaireExerciseBundle/Form/AskerPasswordType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class AskerPasswordType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('password', RepeatedType::class,
                array(
                    'type' => PasswordType::class,
                    'invalid_message' => 'Les mots de passent doivent correspondre.',
                    'options' => array('attr' => array('class' => 'password-filed')),
                    'required' => true,
                    'first_options' => array('label' => 'Mot de passe'),
                    'second_options' => array('label' => 'Confirmer le mot de passe')
                )
            )
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\AskerUser'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'simpleit_claireexercisebundle_askerpassword';
    }
}

src/SimpleIT/ClaireExerciseBundle/Form/AskerUserDirectoryType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use SimpleIT\ClaireExerciseBundle\Repository\DirectoryRepository;
use SimpleIT\ClaireExerciseBundle\Entity\AskerUserDirectory;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;


class AskerUserDirectoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $userId = $options['userId'];
        $builder
            ->add('isReader', CheckboxType::class,
                array(
                    'label' => " ", # do not display "is Manager"
                    'required' => false,
                )
            )
            ->add('isManager', CheckboxType::class,
                array(
                    'label' => " ", # do not display "is Manager"
                    'required' => false,
                )
            )
            ->add('isOwner',CheckboxType::class,
                array(
                    'label' => " ",
                    'disabled' => 'disabled',
                )
            )
            #->add('startDate', HiddenType::class,
            #    array(
            #        'data' => new \DateTime()
            #    )
            #)
            ->add('directory', EntityType::class,
                array(
                    'choice_label' => 'name',
                    'class' => 'SimpleITClaireExerciseBundle:Directory',
                    'query_builder' => function(DirectoryRepository $dr) use($userId){
                        return $dr->findObjects();
                        #return $dr->findObjectNotMine($userId);
                        return $dr->findObjectParents();
                    }
                )
            )

        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\AskerUserDirectory'
        ));
        $resolver->setRequired(array(
            'userId'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'simpleit_claireexercisebundle_askeruserdirectory';
    }
}

src/SimpleIT/ClaireExerciseBundle/Form/AskerUserType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

use Doctrine\Common\Collections\ArrayCollection;

class AskerUserType extends AbstractType
{

    private $em;

    public function __construct($em)
    {
        $this->em = $em;
    }
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $userId = $builder->getData()->getId();
        $datas = new ArrayCollection($this->em
            ->getRepository('SimpleITClaireExerciseBundle:AskerUserDirectory')
            ->findMyParents($userId)
        );
        $builder
            ->add('username', TextType::class,
                array(
                    'label' => 'Identifiant',
                    'block_name' => 'hello'
                )
            )
            ->add('firstName', TextType::class,
                array(
                    'label' => 'Prénom',
                )
            )
            ->add('lastName', TextType::class,
                array(
                    'label' => 'Nom de famille',
                )
            )
            ->add('isEnable', CheckboxType::class,
                array(
                    'label' => 'Compte actif',
                    'required' => false,
                )
            )
            ->add('isLdap', CheckboxType::class,
                array(
                    'label' => 'Compte LDAP',
                    'required' => false,
					'disabled' => true,
                )
            )
            ->add('ldapDn', TextType::class,
                array(
                    'label' => 'DN si compte LDAP',
                    'required' => false,
                )
            )
            ->add('roles', EntityType::class,
                array(
                    'class' => 'SimpleITClaireExerciseBundle:Role',
                    'choice_label' => 'public',
                    'multiple' => true,
                    'expanded' => true,
                )
            )
            ->add('directories',CollectionType::class,
                array(
                    'entry_type' => AskerUserDirectoryType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'data' => $datas,
                    'entry_options' => array(
                        'label' => false,
                        'userId' => $userId
                    )
                )
            )
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\AskerUser'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'simpleit_claireexercisebundle_askeruser';
    }
}

src/SimpleIT/ClaireExerciseBundle/Form/DirectoryType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DirectoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function setDefaultOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\Directory'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'simpleit_claireexercisebundle_directory';
    }
}

src/SimpleIT/ClaireExerciseBundle/Form/ImportFileType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

class ImportFileType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('attachment', FileType::class,
                array(
                    'label' => 'Liste des utilisateurs',
                    'mapped' => false,
                    'required' => true
                )
            )
            ->add('roles', EntityType::class,
                array(
                    'class' => 'SimpleITClaireExerciseBundle:Role',
                    'choice_label' => 'public',
                    'label' => 'Attriber des rôles supplémentaires',
                    'multiple' => true,
                    'expanded' => true,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('r')
                                  ->where('r.name not like :role')
                              ->setParameter('role','%ROLE_USER%');

                    }
                )
            )
            ->add('directory', EntityType::class,
                array(
                    'class' => 'SimpleITClaireExerciseBundle:Directory',
                    'multiple' => false,
                    'expanded' => false,
                    'label' => 'Attribuer un dossier',
                    'placeholder' => "Aucun dossier",
                    'required' => false,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('d')
                        ->where('d.parent is NULL');
                    }
                )
            )
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        #$resolver->setDefaults(array(
        #    'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\AskerUser'
        #));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'simpleit_claireexercisebundle_importfile';
    }
}

src/SimpleIT/ClaireExerciseBundle/Form/StatViewType.php
<?php

namespace SimpleIT\ClaireExerciseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class StatViewType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class,
                array(
                    'label' => 'Nom du filtre',
                )
            )
            ->add('startDate',DateType::class,
                array(
                    'label' => 'Date de début',
                    'widget' => 'single_text',
                )
            )
            ->add('endDate',DateType::class,
                array(
                    'label' => 'Date de fin',
                    'widget' => 'single_text',
                )
            )
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function setDefaultOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SimpleIT\ClaireExerciseBundle\Entity\StatView'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'simpleit_claireexercisebundle_statview';
    }
}

src/SimpleIT/ClaireExerciseBundle/Resources/views/Form/form.html.twig
{% extends "SimpleITClaireExerciseBundle:Frontend:template_creator.html.twig" %}
{% block content %}
  <div class='row'>
    <br>
    <div class='col-xs-4 col-xs-offset-3'>
      {% form_theme form 'bootstrap_3_layout.html.twig' %}
        {{ form_start(form) }}
          {{ form_errors(form) }}
          {{ form_widget(form) }}
          <input type="submit" value="Editer"
          class="btn btn-warning" />
        {{ form_end(form) }}
    </div>
  </div>
{% endblock %}

src/SimpleIT/ClaireExerciseBundle/Resources/views/Form/importUser.html.twig
{% extends "SimpleITClaireExerciseBundle:Frontend:template_creator.html.twig" %}
{% block content %}
  <div class='row'>
    <br>
    <div class='col-xs-6 col-xs-offset-3'>
      {% form_theme form 'bootstrap_3_layout.html.twig' %}
        {{ form_start(form) }}
          {{form_label(form.attachment)}}
          {{form_widget(form.attachment)}}
          {{ form_errors(form) }}
          <p class="help-block">
            Fichier au format CSV avec un ";" comme séparateur pour les comptes externes<br>
            Lyon1: identifiant au format 11234567 ou p1234567<br>
            Extérieur: ext_prenom.nom;password
          </p>
          {{form_row(form.roles)}}
          {{form_row(form.directory)}}
          <input type="submit" value="Envoyer"
          class="btn btn-success" />
        {{ form_end(form) }}
        <br>
        {% for label, messages in app.flashes(['success', 'warning','danger']) %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    {{ message|raw }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>

  </div>
{% endblock %}

src/SimpleIT/ClaireExerciseBundle/Resources/views/Form/lessForm.html.twig
  <div class='row'>
      {% form_theme form 'bootstrap_3_layout.html.twig' %}
        {{ form_start(form) }}
          {{ form_widget(form) }}
          <input type="submit" value="Editer"
          class="btn btn-warning" />
        {{ form_end(form) }}
  </div>

src/SimpleIT/ClaireExerciseBundle/Resources/views/Form/password.html.twig
      {% form_theme form 'bootstrap_3_layout.html.twig' %}
        {{ form_start(form) }}
          {{ form_widget(form) }}
          <input type="submit" value="Sauvegarder"
          class="btn btn-warning" />
        {{ form_end(form) }}

src/SimpleIT/ClaireExerciseBundle/Resources/views/Form/user.html.twig
{% extends "SimpleITClaireExerciseBundle:Frontend:template_creator.html.twig" %}
{% form_theme form _self %}
{# block  options : we remove own dir & subDir#}
{#
    {% set style = "" %}
    {% set selected = '' %}
        {% set selected = "selected=selected" %}
    {% if choice.data.parent is null
    {% if choice.data.owner.id != form.parent.parent.parent.vars.value.id %}
      {% if form.parent.children.directory.vars.value == choice.value %}
#}
{%  block choice_widget %}
  {% for key, choice in form.vars.choices %}
      {% set style = "" %}
      {% set selected = '' %}
      {% if form.parent.children.directory.vars.value == choice.value %}
          {% set selected = "selected" %}
      {% endif %}
      {% if choice.data.parent is not null
       or choice.data.owner.id == form.parent.parent.parent.vars.value.id %}

        {% set style = "display:none;" %}
      {% endif %}

    <option value="{{choice.value}}"
            {{selected}}
            style="{{style}}"
             >{{choice.label}} </option>
  {% endfor %}
{% endblock %}
{# display form insde tr element #}
{% block _simpleit_claireexercisebundle_askeruser_directories_entry_widget %}
      <td>
        <select id="{{form.directory.vars.id}}" name="{{form.directory.vars.full_name}}">
        {{form_widget(form.directory)}}
        </select>
      </td>
      <td>{{form_widget(form.isOwner)}}</td>
      <td>
        {{form_widget(form.isManager)}}
      </td>
      <td>
        {{form_widget(form.isReader)}}
      </td>
  </div>
{% endblock %}
{% block content %}
  <div class='row'>
    <br>
    <div class='col-xs-5 col-xs-offset-3'>
        {{ form_start(form) }}
          {{ form_errors(form) }}
          {{ form_row(form.username,{'attr':{'class':'form-control'}})}}
          {{ form_row(form.firstName,{'attr':{'class':'form-control'}})}}
          {{ form_row(form.lastName,{'attr':{'class':'form-control'}})}}
          {{ form_row(form.isEnable)}}
          {{ form_row(form.isLdap)}}
          {{ form_row(form.ldapDn,{'attr':{'class':'form-control'}})}}
          <div class="form-group">
            <label>Roles</label>
            {% for role in form.roles %}
              <div class="checkbox">
                {{form_row(role)}}
              </div>
            {% endfor %}
          </div>
          <table class="table">
            <thead>
              <th>Répertoires
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"
                title="Il n'est pas possible de supprimer un accés à un propriétaire, ni
                       de changer son statut de propriétaire">
                </span>
              </th>
              <th title="créateur du dossier - non modifiable">Propriétaire</th>
              <th title="Peut modifier le dossier">Responsable</th>
              <th title="Peut lire et importer le dossier">Enseignant</th>
              <th>Action</th>
            </thead>
            <tbody id="tabbody" data-prototype="{{ form_widget(form.directories.vars.prototype)|e('html_attr') }}">
              {% for key, directory in form.directories %}
                {% if
                   directory.vars.data.directory.parent is not null%}
                  {% set style = "display:none;" %}
                {% else %}
                  {% set style = "" %}
                {% endif %}
                <tr style="{{style}}" data-aaowner="{{directory.vars.data.isOwner ? 'true' : 'false'}}">
                  {{ form_widget(directory)}}
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <button type="button" id="add_directory_button" class="btn btn-info">
            <span class="glyphicon glyphicon-plus-sign"></span>
            Dossier supplémentaire
          </button>
          <input type="submit" value="Editer"
          class="btn btn-warning" />
        {{ form_end(form) }}
    </div>
  </div>
<script>
  var $collectionHolder;

// setup an "add a directory" link
var $addDirectoryButton = $("#add_directory_button");
//add the button into this code
var $newLinkLi = $("<div id='div_button' style='margin:5px;'></div>").append($addDirectoryButton);

jQuery(document).ready(function() {
    //var childrens = $('#tabbody').children('select').prop( "disabled", true );
    $('#tabbody select').attr('disabled', true);
    // Get the element that holds the collection of directories
    $collectionHolder = $('#tabbody')

    // add delete link into each elements
    $collectionHolder.find("tr").each(function() {
        addDirectoryFormDeleteLink($(this));
    });

    // append "add a directory" into collectionHolder (table here)
    $collectionHolder.append($newLinkLi);

    // count the current form inputs we have (e.g. 2), use that as the new
    // index when inserting a new item (e.g. 2)
    $collectionHolder.data('index', $collectionHolder.find(':input').length);

    $addDirectoryButton.on('click', function(e) {
        // add a new directory form (see next code block)
        addDirectoryForm($collectionHolder, $newLinkLi);
    });
});
function addDirectoryForm($collectionHolder, $newLinkLi) {
    // Get the data-prototype explained earlier
    var prototype = $collectionHolder.data('prototype');

    // get the new index
    var index = $collectionHolder.data('index');

    var newForm = prototype;

    // Replace '__name__' in the prototype's HTML to
    // instead be a number based on how many items we have
    newForm = newForm.replace(/__name__/g, index);

    // increase the index with one for the next item
    $collectionHolder.data('index', index + 1);

    // Display the form inside HTML markup below
    var $newFormLi = $("<tr></tr>").append(newForm);
    // add the button before the last element
    $newLinkLi.before($newFormLi);
    // add delete button inside form
    addDirectoryFormDeleteLink($newFormLi);
}
function addDirectoryFormDeleteLink($tagFormLi) {
    console.log($tagFormLi[0].dataset.aaowner)
    if($tagFormLi[0].dataset.aaowner === 'true'){
        disabled = 'disabled'

      }else{
        disabled = ''
      }
    var $removeFormButton = $(`<td><button ${disabled} type="button" class="btn btn-xs btn-danger">Supprimer</button></td>`);
    $tagFormLi.append($removeFormButton);
    $removeFormButton.on('click', function(e) {
        // remove the li for the tag form
        $tagFormLi.remove();
    });

}
  $('form').submit(function(e) {
    $(':disabled').each(function(e) {
        $(this).removeAttr('disabled');
    })
});
</script>
{% endblock %}